// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ruijin.proto

package game.mode;

public final class Ruijin {
    private Ruijin() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface RuijinMahjongIntoResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:RuijinMahjongIntoResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 底分
         * </pre>
         * <p>
         * <code>uint32 baseScore = 1;</code>
         */
        int getBaseScore();

        /**
     * <pre>
         *游戏局数
         * </pre>
         *
         * <code>uint32 gameTimes = 2;</code>
         */
        int getGameTimes();

        /**
         * <pre>
         * 人数
         * </pre>
         * <p>
         * <code>uint32 count = 3;</code>
         */
        int getCount();

        /**
         * <pre>
         * 点炮
         * </pre>
         * <p>
         * <code>bool dianpao = 4;</code>
         */
        boolean getDianpao();

        /**
         * <pre>
         * 庄闲
         * </pre>
         * <p>
         * <code>uint32 zhuangxian = 5;</code>
         */
        int getZhuangxian();
    }

    /**
     * <pre>
     * 进入房间返回 ROOM_INFO
     * </pre>
     * <p>
     * Protobuf type {@code RuijinMahjongIntoResponse}
     */
    public static final class RuijinMahjongIntoResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:RuijinMahjongIntoResponse)
            RuijinMahjongIntoResponseOrBuilder {
        // Use RuijinMahjongIntoResponse.newBuilder() to construct.
        private RuijinMahjongIntoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private RuijinMahjongIntoResponse() {
            baseScore_ = 0;
            gameTimes_ = 0;
            count_ = 0;
            dianpao_ = false;
            zhuangxian_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private RuijinMahjongIntoResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            baseScore_ = input.readUInt32();
                            break;
                        }
                        case 16: {

                            gameTimes_ = input.readUInt32();
                            break;
                        }
                        case 24: {

                            count_ = input.readUInt32();
                            break;
                        }
                        case 32: {

                            dianpao_ = input.readBool();
                            break;
                        }
                        case 40: {

                            zhuangxian_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
        makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return game.mode.Ruijin.internal_static_RuijinMahjongIntoResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return game.mode.Ruijin.internal_static_RuijinMahjongIntoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            game.mode.Ruijin.RuijinMahjongIntoResponse.class, game.mode.Ruijin.RuijinMahjongIntoResponse.Builder.class);
        }

        public static final int BASESCORE_FIELD_NUMBER = 1;
        private int baseScore_;

        /**
         * <pre>
         * 底分
         * </pre>
         * <p>
         * <code>uint32 baseScore = 1;</code>
         */
        public int getBaseScore() {
            return baseScore_;
        }

        public static final int GAMETIMES_FIELD_NUMBER = 2;
        private int gameTimes_;

        /**
         * <pre>
         * 游戏局数
         * </pre>
         * <p>
         * <code>uint32 gameTimes = 2;</code>
         */
        public int getGameTimes() {
            return gameTimes_;
        }

        public static final int COUNT_FIELD_NUMBER = 3;
        private int count_;

        /**
         * <pre>
         * 人数
         * </pre>
         * <p>
         * <code>uint32 count = 3;</code>
         */
        public int getCount() {
            return count_;
        }

        public static final int DIANPAO_FIELD_NUMBER = 4;
        private boolean dianpao_;

        /**
         * <pre>
         * 点炮
         * </pre>
         * <p>
         * <code>bool dianpao = 4;</code>
         */
        public boolean getDianpao() {
            return dianpao_;
        }

        public static final int ZHUANGXIAN_FIELD_NUMBER = 5;
        private int zhuangxian_;

        /**
         * <pre>
         * 庄闲
         * </pre>
         * <p>
         * <code>uint32 zhuangxian = 5;</code>
         */
        public int getZhuangxian() {
            return zhuangxian_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (baseScore_ != 0) {
                output.writeUInt32(1, baseScore_);
            }
            if (gameTimes_ != 0) {
                output.writeUInt32(2, gameTimes_);
            }
            if (count_ != 0) {
                output.writeUInt32(3, count_);
            }
            if (dianpao_ != false) {
                output.writeBool(4, dianpao_);
            }
            if (zhuangxian_ != 0) {
                output.writeUInt32(5, zhuangxian_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (baseScore_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, baseScore_);
            }
            if (gameTimes_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, gameTimes_);
            }
            if (count_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, count_);
            }
            if (dianpao_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(4, dianpao_);
            }
            if (zhuangxian_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, zhuangxian_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof game.mode.Ruijin.RuijinMahjongIntoResponse)) {
                return super.equals(obj);
            }
            game.mode.Ruijin.RuijinMahjongIntoResponse other = (game.mode.Ruijin.RuijinMahjongIntoResponse) obj;

            boolean result = true;
            result = result && (getBaseScore()
                    == other.getBaseScore());
            result = result && (getGameTimes()
                    == other.getGameTimes());
            result = result && (getCount()
                    == other.getCount());
            result = result && (getDianpao()
                    == other.getDianpao());
            result = result && (getZhuangxian()
                    == other.getZhuangxian());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + BASESCORE_FIELD_NUMBER;
            hash = (53 * hash) + getBaseScore();
            hash = (37 * hash) + GAMETIMES_FIELD_NUMBER;
            hash = (53 * hash) + getGameTimes();
            hash = (37 * hash) + COUNT_FIELD_NUMBER;
            hash = (53 * hash) + getCount();
            hash = (37 * hash) + DIANPAO_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getDianpao());
            hash = (37 * hash) + ZHUANGXIAN_FIELD_NUMBER;
            hash = (53 * hash) + getZhuangxian();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(game.mode.Ruijin.RuijinMahjongIntoResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 进入房间返回 ROOM_INFO
         * </pre>
         * <p>
         * Protobuf type {@code RuijinMahjongIntoResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:RuijinMahjongIntoResponse)
                game.mode.Ruijin.RuijinMahjongIntoResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return game.mode.Ruijin.internal_static_RuijinMahjongIntoResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return game.mode.Ruijin.internal_static_RuijinMahjongIntoResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                game.mode.Ruijin.RuijinMahjongIntoResponse.class, game.mode.Ruijin.RuijinMahjongIntoResponse.Builder.class);
            }

            // Construct using game.mode.Ruijin.RuijinMahjongIntoResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                baseScore_ = 0;

                gameTimes_ = 0;

                count_ = 0;

                dianpao_ = false;

                zhuangxian_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return game.mode.Ruijin.internal_static_RuijinMahjongIntoResponse_descriptor;
            }

            public game.mode.Ruijin.RuijinMahjongIntoResponse getDefaultInstanceForType() {
                return game.mode.Ruijin.RuijinMahjongIntoResponse.getDefaultInstance();
            }

            public game.mode.Ruijin.RuijinMahjongIntoResponse build() {
                game.mode.Ruijin.RuijinMahjongIntoResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public game.mode.Ruijin.RuijinMahjongIntoResponse buildPartial() {
                game.mode.Ruijin.RuijinMahjongIntoResponse result = new game.mode.Ruijin.RuijinMahjongIntoResponse(this);
                result.baseScore_ = baseScore_;
                result.gameTimes_ = gameTimes_;
                result.count_ = count_;
                result.dianpao_ = dianpao_;
                result.zhuangxian_ = zhuangxian_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof game.mode.Ruijin.RuijinMahjongIntoResponse) {
                    return mergeFrom((game.mode.Ruijin.RuijinMahjongIntoResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(game.mode.Ruijin.RuijinMahjongIntoResponse other) {
                if (other == game.mode.Ruijin.RuijinMahjongIntoResponse.getDefaultInstance()) return this;
                if (other.getBaseScore() != 0) {
                    setBaseScore(other.getBaseScore());
                }
                if (other.getGameTimes() != 0) {
                    setGameTimes(other.getGameTimes());
                }
                if (other.getCount() != 0) {
                    setCount(other.getCount());
                }
                if (other.getDianpao() != false) {
                    setDianpao(other.getDianpao());
                }
                if (other.getZhuangxian() != 0) {
                    setZhuangxian(other.getZhuangxian());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                game.mode.Ruijin.RuijinMahjongIntoResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (game.mode.Ruijin.RuijinMahjongIntoResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int baseScore_;

            /**
             * <pre>
             * 底分
             * </pre>
             * <p>
             * <code>uint32 baseScore = 1;</code>
             */
            public int getBaseScore() {
                return baseScore_;
            }

            /**
             * <pre>
             * 底分
             * </pre>
             * <p>
             * <code>uint32 baseScore = 1;</code>
             */
            public Builder setBaseScore(int value) {

                baseScore_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 底分
             * </pre>
             * <p>
             * <code>uint32 baseScore = 1;</code>
             */
            public Builder clearBaseScore() {

                baseScore_ = 0;
                onChanged();
                return this;
            }

            private int gameTimes_;

            /**
             * <pre>
             * 游戏局数
             * </pre>
             * <p>
             * <code>uint32 gameTimes = 2;</code>
             */
            public int getGameTimes() {
                return gameTimes_;
            }

            /**
             * <pre>
             * 游戏局数
             * </pre>
             * <p>
             * <code>uint32 gameTimes = 2;</code>
             */
            public Builder setGameTimes(int value) {

                gameTimes_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 游戏局数
             * </pre>
             * <p>
             * <code>uint32 gameTimes = 2;</code>
             */
            public Builder clearGameTimes() {

                gameTimes_ = 0;
                onChanged();
                return this;
            }

            private int count_;

            /**
             * <pre>
             * 人数
             * </pre>
             * <p>
             * <code>uint32 count = 3;</code>
             */
            public int getCount() {
                return count_;
            }

            /**
             * <pre>
             * 人数
             * </pre>
             * <p>
             * <code>uint32 count = 3;</code>
             */
            public Builder setCount(int value) {

                count_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 人数
             * </pre>
             * <p>
             * <code>uint32 count = 3;</code>
             */
            public Builder clearCount() {

                count_ = 0;
                onChanged();
                return this;
            }

            private boolean dianpao_;

            /**
             * <pre>
             * 点炮
             * </pre>
             * <p>
             * <code>bool dianpao = 4;</code>
             */
            public boolean getDianpao() {
                return dianpao_;
            }

            /**
             * <pre>
             * 点炮
             * </pre>
             * <p>
             * <code>bool dianpao = 4;</code>
             */
            public Builder setDianpao(boolean value) {

                dianpao_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 点炮
             * </pre>
             * <p>
             * <code>bool dianpao = 4;</code>
             */
            public Builder clearDianpao() {

                dianpao_ = false;
                onChanged();
                return this;
            }

            private int zhuangxian_;

            /**
             * <pre>
             * 庄闲
             * </pre>
             * <p>
             * <code>uint32 zhuangxian = 5;</code>
             */
            public int getZhuangxian() {
                return zhuangxian_;
            }

            /**
             * <pre>
             * 庄闲
             * </pre>
             * <p>
             * <code>uint32 zhuangxian = 5;</code>
             */
            public Builder setZhuangxian(int value) {

                zhuangxian_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 庄闲
             * </pre>
             * <p>
             * <code>uint32 zhuangxian = 5;</code>
             */
            public Builder clearZhuangxian() {

                zhuangxian_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:RuijinMahjongIntoResponse)
        }

        // @@protoc_insertion_point(class_scope:RuijinMahjongIntoResponse)
        private static final game.mode.Ruijin.RuijinMahjongIntoResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new game.mode.Ruijin.RuijinMahjongIntoResponse();
        }

        public static game.mode.Ruijin.RuijinMahjongIntoResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<RuijinMahjongIntoResponse>
                PARSER = new com.google.protobuf.AbstractParser<RuijinMahjongIntoResponse>() {
            public RuijinMahjongIntoResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new RuijinMahjongIntoResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<RuijinMahjongIntoResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<RuijinMahjongIntoResponse> getParserForType() {
            return PARSER;
        }

        public game.mode.Ruijin.RuijinMahjongIntoResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_RuijinMahjongIntoResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_RuijinMahjongIntoResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\014ruijin.proto\"u\n\031RuijinMahjongIntoRespo" +
                        "nse\022\021\n\tbaseScore\030\001 \001(\r\022\021\n\tgameTimes\030\002 \001(" +
                        "\r\022\r\n\005count\030\003 \001(\r\022\017\n\007dianpao\030\004 \001(\010\022\022\n\nzhu" +
                        "angxian\030\005 \001(\rB\013\n\tgame.modeb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_RuijinMahjongIntoResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RuijinMahjongIntoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RuijinMahjongIntoResponse_descriptor,
        new java.lang.String[] { "BaseScore", "GameTimes", "Count", "Dianpao", "Zhuangxian", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
