// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: songjianghe.proto

package game.mode;

public final class Songjianghe {
    private Songjianghe() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface SongjiangheMahjongIntoResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SongjiangheMahjongIntoResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * 基础分
         * </pre>
         * <p>
         * <code>uint32 baseScore = 1;</code>
         */
        int getBaseScore();

        /**
         * <pre>
         * 游戏局数
         * </pre>
         * <p>
         * <code>uint32 gameTimes = 2;</code>
         */
        int getGameTimes();

        /**
         * <pre>
         * 游戏规则  低位到高位到顺序（鸡胡，门清，天地和，幺九，全番，十三幺，对对胡，十八罗汉，七小对，清一色，混一色，海底捞，杠爆全包，庄硬）
         * </pre>
         * <p>
         * <code>uint32 gameRules = 3;</code>
         */
        int getGameRules();

        /**
         * <pre>
         * 1.红中做鬼，2.无鬼，3.翻鬼，4.无鬼加倍
         * </pre>
         * <p>
         * <code>uint32 ghost = 4;</code>
         */
        int getGhost();

        /**
         * <pre>
         * 马数
         * </pre>
         * <p>
         * <code>uint32 maCount = 5;</code>
         */
        int getMaCount();

        /**
         * <pre>
         * 人数
         * </pre>
         * <p>
         * <code>uint32 count = 6;</code>
         */
        int getCount();
    }

    /**
     * <pre>
     * 进入房间返回 ROOM_INFO
     * </pre>
     * <p>
     * Protobuf type {@code SongjiangheMahjongIntoResponse}
     */
    public static final class SongjiangheMahjongIntoResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:SongjiangheMahjongIntoResponse)
            SongjiangheMahjongIntoResponseOrBuilder {
        // Use SongjiangheMahjongIntoResponse.newBuilder() to construct.
        private SongjiangheMahjongIntoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SongjiangheMahjongIntoResponse() {
            baseScore_ = 0;
            gameTimes_ = 0;
            gameRules_ = 0;
            ghost_ = 0;
            maCount_ = 0;
            count_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private SongjiangheMahjongIntoResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            baseScore_ = input.readUInt32();
                            break;
                        }
                        case 16: {

                            gameTimes_ = input.readUInt32();
                            break;
                        }
                        case 24: {

                            gameRules_ = input.readUInt32();
                            break;
                        }
                        case 32: {

                            ghost_ = input.readUInt32();
                            break;
                        }
                        case 40: {

                            maCount_ = input.readUInt32();
                            break;
                        }
                        case 48: {

                            count_ = input.readUInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return game.mode.Songjianghe.internal_static_SongjiangheMahjongIntoResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return game.mode.Songjianghe.internal_static_SongjiangheMahjongIntoResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            game.mode.Songjianghe.SongjiangheMahjongIntoResponse.class, game.mode.Songjianghe.SongjiangheMahjongIntoResponse.Builder.class);
        }

        public static final int BASESCORE_FIELD_NUMBER = 1;
        private int baseScore_;

        /**
         * <pre>
         * 基础分
         * </pre>
         * <p>
         * <code>uint32 baseScore = 1;</code>
         */
        public int getBaseScore() {
            return baseScore_;
        }

        public static final int GAMETIMES_FIELD_NUMBER = 2;
        private int gameTimes_;

        /**
         * <pre>
         * 游戏局数
         * </pre>
         * <p>
         * <code>uint32 gameTimes = 2;</code>
         */
        public int getGameTimes() {
            return gameTimes_;
        }

        public static final int GAMERULES_FIELD_NUMBER = 3;
        private int gameRules_;

        /**
         * <pre>
         * 游戏规则  低位到高位到顺序（鸡胡，门清，天地和，幺九，全番，十三幺，对对胡，十八罗汉，七小对，清一色，混一色，海底捞，杠爆全包，庄硬）
         * </pre>
         * <p>
         * <code>uint32 gameRules = 3;</code>
         */
        public int getGameRules() {
            return gameRules_;
        }

        public static final int GHOST_FIELD_NUMBER = 4;
        private int ghost_;

        /**
         * <pre>
         * 1.红中做鬼，2.无鬼，3.翻鬼，4.无鬼加倍
         * </pre>
         * <p>
         * <code>uint32 ghost = 4;</code>
         */
        public int getGhost() {
            return ghost_;
        }

        public static final int MACOUNT_FIELD_NUMBER = 5;
        private int maCount_;

        /**
         * <pre>
         * 马数
         * </pre>
         * <p>
         * <code>uint32 maCount = 5;</code>
         */
        public int getMaCount() {
            return maCount_;
        }

        public static final int COUNT_FIELD_NUMBER = 6;
        private int count_;

        /**
         * <pre>
         * 人数
         * </pre>
         * <p>
         * <code>uint32 count = 6;</code>
         */
        public int getCount() {
            return count_;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (baseScore_ != 0) {
                output.writeUInt32(1, baseScore_);
            }
            if (gameTimes_ != 0) {
                output.writeUInt32(2, gameTimes_);
            }
            if (gameRules_ != 0) {
                output.writeUInt32(3, gameRules_);
            }
            if (ghost_ != 0) {
                output.writeUInt32(4, ghost_);
            }
            if (maCount_ != 0) {
                output.writeUInt32(5, maCount_);
            }
            if (count_ != 0) {
                output.writeUInt32(6, count_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (baseScore_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, baseScore_);
            }
            if (gameTimes_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, gameTimes_);
            }
            if (gameRules_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, gameRules_);
            }
            if (ghost_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(4, ghost_);
            }
            if (maCount_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, maCount_);
            }
            if (count_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, count_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof game.mode.Songjianghe.SongjiangheMahjongIntoResponse)) {
                return super.equals(obj);
            }
            game.mode.Songjianghe.SongjiangheMahjongIntoResponse other = (game.mode.Songjianghe.SongjiangheMahjongIntoResponse) obj;

            boolean result = true;
            result = result && (getBaseScore()
                    == other.getBaseScore());
            result = result && (getGameTimes()
                    == other.getGameTimes());
            result = result && (getGameRules()
                    == other.getGameRules());
            result = result && (getGhost()
                    == other.getGhost());
            result = result && (getMaCount()
                    == other.getMaCount());
            result = result && (getCount()
                    == other.getCount());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + BASESCORE_FIELD_NUMBER;
            hash = (53 * hash) + getBaseScore();
            hash = (37 * hash) + GAMETIMES_FIELD_NUMBER;
            hash = (53 * hash) + getGameTimes();
            hash = (37 * hash) + GAMERULES_FIELD_NUMBER;
            hash = (53 * hash) + getGameRules();
            hash = (37 * hash) + GHOST_FIELD_NUMBER;
            hash = (53 * hash) + getGhost();
            hash = (37 * hash) + MACOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getMaCount();
            hash = (37 * hash) + COUNT_FIELD_NUMBER;
            hash = (53 * hash) + getCount();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(game.mode.Songjianghe.SongjiangheMahjongIntoResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 进入房间返回 ROOM_INFO
         * </pre>
         * <p>
         * Protobuf type {@code SongjiangheMahjongIntoResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:SongjiangheMahjongIntoResponse)
                game.mode.Songjianghe.SongjiangheMahjongIntoResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return game.mode.Songjianghe.internal_static_SongjiangheMahjongIntoResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return game.mode.Songjianghe.internal_static_SongjiangheMahjongIntoResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                game.mode.Songjianghe.SongjiangheMahjongIntoResponse.class, game.mode.Songjianghe.SongjiangheMahjongIntoResponse.Builder.class);
            }

            // Construct using game.mode.Songjianghe.SongjiangheMahjongIntoResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                baseScore_ = 0;

                gameTimes_ = 0;

                gameRules_ = 0;

                ghost_ = 0;

                maCount_ = 0;

                count_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return game.mode.Songjianghe.internal_static_SongjiangheMahjongIntoResponse_descriptor;
            }

            public game.mode.Songjianghe.SongjiangheMahjongIntoResponse getDefaultInstanceForType() {
                return game.mode.Songjianghe.SongjiangheMahjongIntoResponse.getDefaultInstance();
            }

            public game.mode.Songjianghe.SongjiangheMahjongIntoResponse build() {
                game.mode.Songjianghe.SongjiangheMahjongIntoResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public game.mode.Songjianghe.SongjiangheMahjongIntoResponse buildPartial() {
                game.mode.Songjianghe.SongjiangheMahjongIntoResponse result = new game.mode.Songjianghe.SongjiangheMahjongIntoResponse(this);
                result.baseScore_ = baseScore_;
                result.gameTimes_ = gameTimes_;
                result.gameRules_ = gameRules_;
                result.ghost_ = ghost_;
                result.maCount_ = maCount_;
                result.count_ = count_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof game.mode.Songjianghe.SongjiangheMahjongIntoResponse) {
                    return mergeFrom((game.mode.Songjianghe.SongjiangheMahjongIntoResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(game.mode.Songjianghe.SongjiangheMahjongIntoResponse other) {
                if (other == game.mode.Songjianghe.SongjiangheMahjongIntoResponse.getDefaultInstance()) return this;
                if (other.getBaseScore() != 0) {
                    setBaseScore(other.getBaseScore());
                }
                if (other.getGameTimes() != 0) {
                    setGameTimes(other.getGameTimes());
                }
                if (other.getGameRules() != 0) {
                    setGameRules(other.getGameRules());
                }
                if (other.getGhost() != 0) {
                    setGhost(other.getGhost());
                }
                if (other.getMaCount() != 0) {
                    setMaCount(other.getMaCount());
                }
                if (other.getCount() != 0) {
                    setCount(other.getCount());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                game.mode.Songjianghe.SongjiangheMahjongIntoResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (game.mode.Songjianghe.SongjiangheMahjongIntoResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int baseScore_;

            /**
             * <pre>
             * 基础分
             * </pre>
             * <p>
             * <code>uint32 baseScore = 1;</code>
             */
            public int getBaseScore() {
                return baseScore_;
            }

            /**
             * <pre>
             * 基础分
             * </pre>
             * <p>
             * <code>uint32 baseScore = 1;</code>
             */
            public Builder setBaseScore(int value) {

                baseScore_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 基础分
             * </pre>
             * <p>
             * <code>uint32 baseScore = 1;</code>
             */
            public Builder clearBaseScore() {

                baseScore_ = 0;
                onChanged();
                return this;
            }

            private int gameTimes_;

            /**
             * <pre>
             * 游戏局数
             * </pre>
             * <p>
             * <code>uint32 gameTimes = 2;</code>
             */
            public int getGameTimes() {
                return gameTimes_;
            }

            /**
             * <pre>
             * 游戏局数
             * </pre>
             * <p>
             * <code>uint32 gameTimes = 2;</code>
             */
            public Builder setGameTimes(int value) {

                gameTimes_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 游戏局数
             * </pre>
             * <p>
             * <code>uint32 gameTimes = 2;</code>
             */
            public Builder clearGameTimes() {

                gameTimes_ = 0;
                onChanged();
                return this;
            }

            private int gameRules_;

            /**
             * <pre>
             * 游戏规则  低位到高位到顺序（鸡胡，门清，天地和，幺九，全番，十三幺，对对胡，十八罗汉，七小对，清一色，混一色，海底捞，杠爆全包，庄硬）
             * </pre>
             * <p>
             * <code>uint32 gameRules = 3;</code>
             */
            public int getGameRules() {
                return gameRules_;
            }

            /**
             * <pre>
             * 游戏规则  低位到高位到顺序（鸡胡，门清，天地和，幺九，全番，十三幺，对对胡，十八罗汉，七小对，清一色，混一色，海底捞，杠爆全包，庄硬）
             * </pre>
             * <p>
             * <code>uint32 gameRules = 3;</code>
             */
            public Builder setGameRules(int value) {

                gameRules_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 游戏规则  低位到高位到顺序（鸡胡，门清，天地和，幺九，全番，十三幺，对对胡，十八罗汉，七小对，清一色，混一色，海底捞，杠爆全包，庄硬）
             * </pre>
             * <p>
             * <code>uint32 gameRules = 3;</code>
             */
            public Builder clearGameRules() {

                gameRules_ = 0;
                onChanged();
                return this;
            }

            private int ghost_;

            /**
             * <pre>
             * 1.红中做鬼，2.无鬼，3.翻鬼，4.无鬼加倍
             * </pre>
             * <p>
             * <code>uint32 ghost = 4;</code>
             */
            public int getGhost() {
                return ghost_;
            }

            /**
             * <pre>
             * 1.红中做鬼，2.无鬼，3.翻鬼，4.无鬼加倍
             * </pre>
             * <p>
             * <code>uint32 ghost = 4;</code>
             */
            public Builder setGhost(int value) {

                ghost_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 1.红中做鬼，2.无鬼，3.翻鬼，4.无鬼加倍
             * </pre>
             * <p>
             * <code>uint32 ghost = 4;</code>
             */
            public Builder clearGhost() {

                ghost_ = 0;
                onChanged();
                return this;
            }

            private int maCount_;

            /**
             * <pre>
             * 马数
             * </pre>
             * <p>
             * <code>uint32 maCount = 5;</code>
             */
            public int getMaCount() {
                return maCount_;
            }

            /**
             * <pre>
             * 马数
             * </pre>
             * <p>
             * <code>uint32 maCount = 5;</code>
             */
            public Builder setMaCount(int value) {

                maCount_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 马数
             * </pre>
             * <p>
             * <code>uint32 maCount = 5;</code>
             */
            public Builder clearMaCount() {

                maCount_ = 0;
                onChanged();
                return this;
            }

            private int count_;

            /**
             * <pre>
             * 人数
             * </pre>
             * <p>
             * <code>uint32 count = 6;</code>
             */
            public int getCount() {
                return count_;
            }

            /**
             * <pre>
             * 人数
             * </pre>
             * <p>
             * <code>uint32 count = 6;</code>
             */
            public Builder setCount(int value) {

                count_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * 人数
             * </pre>
             * <p>
             * <code>uint32 count = 6;</code>
             */
            public Builder clearCount() {

                count_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:SongjiangheMahjongIntoResponse)
        }

        // @@protoc_insertion_point(class_scope:SongjiangheMahjongIntoResponse)
        private static final game.mode.Songjianghe.SongjiangheMahjongIntoResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new game.mode.Songjianghe.SongjiangheMahjongIntoResponse();
        }

        public static game.mode.Songjianghe.SongjiangheMahjongIntoResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SongjiangheMahjongIntoResponse>
                PARSER = new com.google.protobuf.AbstractParser<SongjiangheMahjongIntoResponse>() {
            public SongjiangheMahjongIntoResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SongjiangheMahjongIntoResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SongjiangheMahjongIntoResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SongjiangheMahjongIntoResponse> getParserForType() {
            return PARSER;
        }

        public game.mode.Songjianghe.SongjiangheMahjongIntoResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface SongjiangheMahjongReplayResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:SongjiangheMahjongReplayResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>.MahjongStartResponse start = 1;</code>
         */
        boolean hasStart();

        /**
         * <code>.MahjongStartResponse start = 1;</code>
         */
        game.mode.Mahjong.MahjongStartResponse getStart();

        /**
         * <code>.MahjongStartResponse start = 1;</code>
         */
        game.mode.Mahjong.MahjongStartResponseOrBuilder getStartOrBuilder();

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        java.util.List<game.mode.GameBase.OperationHistory>
        getHistoryList();

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        game.mode.GameBase.OperationHistory getHistory(int index);

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        int getHistoryCount();

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        java.util.List<? extends game.mode.GameBase.OperationHistoryOrBuilder>
        getHistoryOrBuilderList();

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        game.mode.GameBase.OperationHistoryOrBuilder getHistoryOrBuilder(
                int index);

        /**
         * <code>.MahjongResultResponse result = 3;</code>
         */
        boolean hasResult();

        /**
         * <code>.MahjongResultResponse result = 3;</code>
         */
        game.mode.Mahjong.MahjongResultResponse getResult();

        /**
         * <code>.MahjongResultResponse result = 3;</code>
         */
        game.mode.Mahjong.MahjongResultResponseOrBuilder getResultOrBuilder();
    }

    /**
     * <pre>
     * 回放    REPLAY
     * </pre>
     * <p>
     * Protobuf type {@code SongjiangheMahjongReplayResponse}
     */
    public static final class SongjiangheMahjongReplayResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:SongjiangheMahjongReplayResponse)
            SongjiangheMahjongReplayResponseOrBuilder {
        // Use SongjiangheMahjongReplayResponse.newBuilder() to construct.
        private SongjiangheMahjongReplayResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private SongjiangheMahjongReplayResponse() {
            history_ = java.util.Collections.emptyList();
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private SongjiangheMahjongReplayResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            game.mode.Mahjong.MahjongStartResponse.Builder subBuilder = null;
                            if (start_ != null) {
                                subBuilder = start_.toBuilder();
                            }
                            start_ = input.readMessage(game.mode.Mahjong.MahjongStartResponse.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(start_);
                                start_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                        case 18: {
                            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                                history_ = new java.util.ArrayList<game.mode.GameBase.OperationHistory>();
                                mutable_bitField0_ |= 0x00000002;
                            }
                            history_.add(
                                    input.readMessage(game.mode.GameBase.OperationHistory.parser(), extensionRegistry));
                            break;
                        }
                        case 26: {
                            game.mode.Mahjong.MahjongResultResponse.Builder subBuilder = null;
                            if (result_ != null) {
                                subBuilder = result_.toBuilder();
                            }
                            result_ = input.readMessage(game.mode.Mahjong.MahjongResultResponse.parser(), extensionRegistry);
                            if (subBuilder != null) {
                                subBuilder.mergeFrom(result_);
                                result_ = subBuilder.buildPartial();
                            }

                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                    history_ = java.util.Collections.unmodifiableList(history_);
                }
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return game.mode.Songjianghe.internal_static_SongjiangheMahjongReplayResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return game.mode.Songjianghe.internal_static_SongjiangheMahjongReplayResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            game.mode.Songjianghe.SongjiangheMahjongReplayResponse.class, game.mode.Songjianghe.SongjiangheMahjongReplayResponse.Builder.class);
        }

        private int bitField0_;
        public static final int START_FIELD_NUMBER = 1;
        private game.mode.Mahjong.MahjongStartResponse start_;

        /**
         * <code>.MahjongStartResponse start = 1;</code>
         */
        public boolean hasStart() {
            return start_ != null;
        }

        /**
         * <code>.MahjongStartResponse start = 1;</code>
         */
        public game.mode.Mahjong.MahjongStartResponse getStart() {
            return start_ == null ? game.mode.Mahjong.MahjongStartResponse.getDefaultInstance() : start_;
        }

        /**
         * <code>.MahjongStartResponse start = 1;</code>
         */
        public game.mode.Mahjong.MahjongStartResponseOrBuilder getStartOrBuilder() {
            return getStart();
        }

        public static final int HISTORY_FIELD_NUMBER = 2;
        private java.util.List<game.mode.GameBase.OperationHistory> history_;

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        public java.util.List<game.mode.GameBase.OperationHistory> getHistoryList() {
            return history_;
        }

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        public java.util.List<? extends game.mode.GameBase.OperationHistoryOrBuilder>
        getHistoryOrBuilderList() {
            return history_;
        }

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        public int getHistoryCount() {
            return history_.size();
        }

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        public game.mode.GameBase.OperationHistory getHistory(int index) {
            return history_.get(index);
        }

        /**
         * <pre>
         * 操作记录
         * </pre>
         * <p>
         * <code>repeated .OperationHistory history = 2;</code>
         */
        public game.mode.GameBase.OperationHistoryOrBuilder getHistoryOrBuilder(
                int index) {
            return history_.get(index);
        }

        public static final int RESULT_FIELD_NUMBER = 3;
        private game.mode.Mahjong.MahjongResultResponse result_;

        /**
         * <code>.MahjongResultResponse result = 3;</code>
         */
        public boolean hasResult() {
            return result_ != null;
        }

        /**
         * <code>.MahjongResultResponse result = 3;</code>
         */
        public game.mode.Mahjong.MahjongResultResponse getResult() {
            return result_ == null ? game.mode.Mahjong.MahjongResultResponse.getDefaultInstance() : result_;
        }

        /**
         * <code>.MahjongResultResponse result = 3;</code>
         */
        public game.mode.Mahjong.MahjongResultResponseOrBuilder getResultOrBuilder() {
            return getResult();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (start_ != null) {
                output.writeMessage(1, getStart());
            }
            for (int i = 0; i < history_.size(); i++) {
                output.writeMessage(2, history_.get(i));
            }
            if (result_ != null) {
                output.writeMessage(3, getResult());
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (start_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, getStart());
            }
            for (int i = 0; i < history_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(2, history_.get(i));
            }
            if (result_ != null) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(3, getResult());
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof game.mode.Songjianghe.SongjiangheMahjongReplayResponse)) {
                return super.equals(obj);
            }
            game.mode.Songjianghe.SongjiangheMahjongReplayResponse other = (game.mode.Songjianghe.SongjiangheMahjongReplayResponse) obj;

            boolean result = true;
            result = result && (hasStart() == other.hasStart());
            if (hasStart()) {
                result = result && getStart()
                        .equals(other.getStart());
            }
            result = result && getHistoryList()
                    .equals(other.getHistoryList());
            result = result && (hasResult() == other.hasResult());
            if (hasResult()) {
                result = result && getResult()
                        .equals(other.getResult());
            }
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasStart()) {
                hash = (37 * hash) + START_FIELD_NUMBER;
                hash = (53 * hash) + getStart().hashCode();
            }
            if (getHistoryCount() > 0) {
                hash = (37 * hash) + HISTORY_FIELD_NUMBER;
                hash = (53 * hash) + getHistoryList().hashCode();
            }
            if (hasResult()) {
                hash = (37 * hash) + RESULT_FIELD_NUMBER;
                hash = (53 * hash) + getResult().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(game.mode.Songjianghe.SongjiangheMahjongReplayResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * <pre>
         * 回放    REPLAY
         * </pre>
         * <p>
         * Protobuf type {@code SongjiangheMahjongReplayResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:SongjiangheMahjongReplayResponse)
                game.mode.Songjianghe.SongjiangheMahjongReplayResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return game.mode.Songjianghe.internal_static_SongjiangheMahjongReplayResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return game.mode.Songjianghe.internal_static_SongjiangheMahjongReplayResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                game.mode.Songjianghe.SongjiangheMahjongReplayResponse.class, game.mode.Songjianghe.SongjiangheMahjongReplayResponse.Builder.class);
            }

            // Construct using game.mode.Songjianghe.SongjiangheMahjongReplayResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                    getHistoryFieldBuilder();
                }
            }

            public Builder clear() {
                super.clear();
                if (startBuilder_ == null) {
                    start_ = null;
                } else {
                    start_ = null;
                    startBuilder_ = null;
                }
                if (historyBuilder_ == null) {
                    history_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                } else {
                    historyBuilder_.clear();
                }
                if (resultBuilder_ == null) {
                    result_ = null;
                } else {
                    result_ = null;
                    resultBuilder_ = null;
                }
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return game.mode.Songjianghe.internal_static_SongjiangheMahjongReplayResponse_descriptor;
            }

            public game.mode.Songjianghe.SongjiangheMahjongReplayResponse getDefaultInstanceForType() {
                return game.mode.Songjianghe.SongjiangheMahjongReplayResponse.getDefaultInstance();
            }

            public game.mode.Songjianghe.SongjiangheMahjongReplayResponse build() {
                game.mode.Songjianghe.SongjiangheMahjongReplayResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public game.mode.Songjianghe.SongjiangheMahjongReplayResponse buildPartial() {
                game.mode.Songjianghe.SongjiangheMahjongReplayResponse result = new game.mode.Songjianghe.SongjiangheMahjongReplayResponse(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (startBuilder_ == null) {
                    result.start_ = start_;
                } else {
                    result.start_ = startBuilder_.build();
                }
                if (historyBuilder_ == null) {
                    if (((bitField0_ & 0x00000002) == 0x00000002)) {
                        history_ = java.util.Collections.unmodifiableList(history_);
                        bitField0_ = (bitField0_ & ~0x00000002);
                    }
                    result.history_ = history_;
                } else {
                    result.history_ = historyBuilder_.build();
                }
                if (resultBuilder_ == null) {
                    result.result_ = result_;
                } else {
                    result.result_ = resultBuilder_.build();
                }
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof game.mode.Songjianghe.SongjiangheMahjongReplayResponse) {
                    return mergeFrom((game.mode.Songjianghe.SongjiangheMahjongReplayResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(game.mode.Songjianghe.SongjiangheMahjongReplayResponse other) {
                if (other == game.mode.Songjianghe.SongjiangheMahjongReplayResponse.getDefaultInstance()) return this;
                if (other.hasStart()) {
                    mergeStart(other.getStart());
                }
                if (historyBuilder_ == null) {
                    if (!other.history_.isEmpty()) {
                        if (history_.isEmpty()) {
                            history_ = other.history_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                        } else {
                            ensureHistoryIsMutable();
                            history_.addAll(other.history_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.history_.isEmpty()) {
                        if (historyBuilder_.isEmpty()) {
                            historyBuilder_.dispose();
                            historyBuilder_ = null;
                            history_ = other.history_;
                            bitField0_ = (bitField0_ & ~0x00000002);
                            historyBuilder_ =
                                    com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                                            getHistoryFieldBuilder() : null;
                        } else {
                            historyBuilder_.addAllMessages(other.history_);
                        }
                    }
                }
                if (other.hasResult()) {
                    mergeResult(other.getResult());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                game.mode.Songjianghe.SongjiangheMahjongReplayResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (game.mode.Songjianghe.SongjiangheMahjongReplayResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private game.mode.Mahjong.MahjongStartResponse start_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    game.mode.Mahjong.MahjongStartResponse, game.mode.Mahjong.MahjongStartResponse.Builder, game.mode.Mahjong.MahjongStartResponseOrBuilder> startBuilder_;

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public boolean hasStart() {
                return startBuilder_ != null || start_ != null;
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public game.mode.Mahjong.MahjongStartResponse getStart() {
                if (startBuilder_ == null) {
                    return start_ == null ? game.mode.Mahjong.MahjongStartResponse.getDefaultInstance() : start_;
                } else {
                    return startBuilder_.getMessage();
                }
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public Builder setStart(game.mode.Mahjong.MahjongStartResponse value) {
                if (startBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    start_ = value;
                    onChanged();
                } else {
                    startBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public Builder setStart(
                    game.mode.Mahjong.MahjongStartResponse.Builder builderForValue) {
                if (startBuilder_ == null) {
                    start_ = builderForValue.build();
                    onChanged();
                } else {
                    startBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public Builder mergeStart(game.mode.Mahjong.MahjongStartResponse value) {
                if (startBuilder_ == null) {
                    if (start_ != null) {
                        start_ =
                                game.mode.Mahjong.MahjongStartResponse.newBuilder(start_).mergeFrom(value).buildPartial();
                    } else {
                        start_ = value;
                    }
                    onChanged();
                } else {
                    startBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public Builder clearStart() {
                if (startBuilder_ == null) {
                    start_ = null;
                    onChanged();
                } else {
                    start_ = null;
                    startBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public game.mode.Mahjong.MahjongStartResponse.Builder getStartBuilder() {

                onChanged();
                return getStartFieldBuilder().getBuilder();
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            public game.mode.Mahjong.MahjongStartResponseOrBuilder getStartOrBuilder() {
                if (startBuilder_ != null) {
                    return startBuilder_.getMessageOrBuilder();
                } else {
                    return start_ == null ?
                            game.mode.Mahjong.MahjongStartResponse.getDefaultInstance() : start_;
                }
            }

            /**
             * <code>.MahjongStartResponse start = 1;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    game.mode.Mahjong.MahjongStartResponse, game.mode.Mahjong.MahjongStartResponse.Builder, game.mode.Mahjong.MahjongStartResponseOrBuilder>
            getStartFieldBuilder() {
                if (startBuilder_ == null) {
                    startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            game.mode.Mahjong.MahjongStartResponse, game.mode.Mahjong.MahjongStartResponse.Builder, game.mode.Mahjong.MahjongStartResponseOrBuilder>(
                            getStart(),
                            getParentForChildren(),
                            isClean());
                    start_ = null;
                }
                return startBuilder_;
            }

            private java.util.List<game.mode.GameBase.OperationHistory> history_ =
                    java.util.Collections.emptyList();

            private void ensureHistoryIsMutable() {
                if (!((bitField0_ & 0x00000002) == 0x00000002)) {
                    history_ = new java.util.ArrayList<game.mode.GameBase.OperationHistory>(history_);
                    bitField0_ |= 0x00000002;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    game.mode.GameBase.OperationHistory, game.mode.GameBase.OperationHistory.Builder, game.mode.GameBase.OperationHistoryOrBuilder> historyBuilder_;

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public java.util.List<game.mode.GameBase.OperationHistory> getHistoryList() {
                if (historyBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(history_);
                } else {
                    return historyBuilder_.getMessageList();
                }
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public int getHistoryCount() {
                if (historyBuilder_ == null) {
                    return history_.size();
                } else {
                    return historyBuilder_.getCount();
                }
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public game.mode.GameBase.OperationHistory getHistory(int index) {
                if (historyBuilder_ == null) {
                    return history_.get(index);
                } else {
                    return historyBuilder_.getMessage(index);
                }
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder setHistory(
                    int index, game.mode.GameBase.OperationHistory value) {
                if (historyBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHistoryIsMutable();
                    history_.set(index, value);
                    onChanged();
                } else {
                    historyBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder setHistory(
                    int index, game.mode.GameBase.OperationHistory.Builder builderForValue) {
                if (historyBuilder_ == null) {
                    ensureHistoryIsMutable();
                    history_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    historyBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder addHistory(game.mode.GameBase.OperationHistory value) {
                if (historyBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHistoryIsMutable();
                    history_.add(value);
                    onChanged();
                } else {
                    historyBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder addHistory(
                    int index, game.mode.GameBase.OperationHistory value) {
                if (historyBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureHistoryIsMutable();
                    history_.add(index, value);
                    onChanged();
                } else {
                    historyBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder addHistory(
                    game.mode.GameBase.OperationHistory.Builder builderForValue) {
                if (historyBuilder_ == null) {
                    ensureHistoryIsMutable();
                    history_.add(builderForValue.build());
                    onChanged();
                } else {
                    historyBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder addHistory(
                    int index, game.mode.GameBase.OperationHistory.Builder builderForValue) {
                if (historyBuilder_ == null) {
                    ensureHistoryIsMutable();
                    history_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    historyBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder addAllHistory(
                    java.lang.Iterable<? extends game.mode.GameBase.OperationHistory> values) {
                if (historyBuilder_ == null) {
                    ensureHistoryIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, history_);
                    onChanged();
                } else {
                    historyBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder clearHistory() {
                if (historyBuilder_ == null) {
                    history_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000002);
                    onChanged();
                } else {
                    historyBuilder_.clear();
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public Builder removeHistory(int index) {
                if (historyBuilder_ == null) {
                    ensureHistoryIsMutable();
                    history_.remove(index);
                    onChanged();
                } else {
                    historyBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public game.mode.GameBase.OperationHistory.Builder getHistoryBuilder(
                    int index) {
                return getHistoryFieldBuilder().getBuilder(index);
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public game.mode.GameBase.OperationHistoryOrBuilder getHistoryOrBuilder(
                    int index) {
                if (historyBuilder_ == null) {
                    return history_.get(index);
                } else {
                    return historyBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public java.util.List<? extends game.mode.GameBase.OperationHistoryOrBuilder>
            getHistoryOrBuilderList() {
                if (historyBuilder_ != null) {
                    return historyBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(history_);
                }
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public game.mode.GameBase.OperationHistory.Builder addHistoryBuilder() {
                return getHistoryFieldBuilder().addBuilder(
                        game.mode.GameBase.OperationHistory.getDefaultInstance());
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public game.mode.GameBase.OperationHistory.Builder addHistoryBuilder(
                    int index) {
                return getHistoryFieldBuilder().addBuilder(
                        index, game.mode.GameBase.OperationHistory.getDefaultInstance());
            }

            /**
             * <pre>
             * 操作记录
             * </pre>
             * <p>
             * <code>repeated .OperationHistory history = 2;</code>
             */
            public java.util.List<game.mode.GameBase.OperationHistory.Builder>
            getHistoryBuilderList() {
                return getHistoryFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilderV3<
                    game.mode.GameBase.OperationHistory, game.mode.GameBase.OperationHistory.Builder, game.mode.GameBase.OperationHistoryOrBuilder>
            getHistoryFieldBuilder() {
                if (historyBuilder_ == null) {
                    historyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                            game.mode.GameBase.OperationHistory, game.mode.GameBase.OperationHistory.Builder, game.mode.GameBase.OperationHistoryOrBuilder>(
                            history_,
                            ((bitField0_ & 0x00000002) == 0x00000002),
                            getParentForChildren(),
                            isClean());
                    history_ = null;
                }
                return historyBuilder_;
            }

            private game.mode.Mahjong.MahjongResultResponse result_ = null;
            private com.google.protobuf.SingleFieldBuilderV3<
                    game.mode.Mahjong.MahjongResultResponse, game.mode.Mahjong.MahjongResultResponse.Builder, game.mode.Mahjong.MahjongResultResponseOrBuilder> resultBuilder_;

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public boolean hasResult() {
                return resultBuilder_ != null || result_ != null;
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public game.mode.Mahjong.MahjongResultResponse getResult() {
                if (resultBuilder_ == null) {
                    return result_ == null ? game.mode.Mahjong.MahjongResultResponse.getDefaultInstance() : result_;
                } else {
                    return resultBuilder_.getMessage();
                }
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public Builder setResult(game.mode.Mahjong.MahjongResultResponse value) {
                if (resultBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    result_ = value;
                    onChanged();
                } else {
                    resultBuilder_.setMessage(value);
                }

                return this;
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public Builder setResult(
                    game.mode.Mahjong.MahjongResultResponse.Builder builderForValue) {
                if (resultBuilder_ == null) {
                    result_ = builderForValue.build();
                    onChanged();
                } else {
                    resultBuilder_.setMessage(builderForValue.build());
                }

                return this;
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public Builder mergeResult(game.mode.Mahjong.MahjongResultResponse value) {
                if (resultBuilder_ == null) {
                    if (result_ != null) {
                        result_ =
                                game.mode.Mahjong.MahjongResultResponse.newBuilder(result_).mergeFrom(value).buildPartial();
                    } else {
                        result_ = value;
                    }
                    onChanged();
                } else {
                    resultBuilder_.mergeFrom(value);
                }

                return this;
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public Builder clearResult() {
                if (resultBuilder_ == null) {
                    result_ = null;
                    onChanged();
                } else {
                    result_ = null;
                    resultBuilder_ = null;
                }

                return this;
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public game.mode.Mahjong.MahjongResultResponse.Builder getResultBuilder() {

                onChanged();
                return getResultFieldBuilder().getBuilder();
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            public game.mode.Mahjong.MahjongResultResponseOrBuilder getResultOrBuilder() {
                if (resultBuilder_ != null) {
                    return resultBuilder_.getMessageOrBuilder();
                } else {
                    return result_ == null ?
                            game.mode.Mahjong.MahjongResultResponse.getDefaultInstance() : result_;
                }
            }

            /**
             * <code>.MahjongResultResponse result = 3;</code>
             */
            private com.google.protobuf.SingleFieldBuilderV3<
                    game.mode.Mahjong.MahjongResultResponse, game.mode.Mahjong.MahjongResultResponse.Builder, game.mode.Mahjong.MahjongResultResponseOrBuilder>
            getResultFieldBuilder() {
                if (resultBuilder_ == null) {
                    resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                            game.mode.Mahjong.MahjongResultResponse, game.mode.Mahjong.MahjongResultResponse.Builder, game.mode.Mahjong.MahjongResultResponseOrBuilder>(
                            getResult(),
                            getParentForChildren(),
                            isClean());
                    result_ = null;
                }
                return resultBuilder_;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:SongjiangheMahjongReplayResponse)
        }

        // @@protoc_insertion_point(class_scope:SongjiangheMahjongReplayResponse)
        private static final game.mode.Songjianghe.SongjiangheMahjongReplayResponse DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new game.mode.Songjianghe.SongjiangheMahjongReplayResponse();
        }

        public static game.mode.Songjianghe.SongjiangheMahjongReplayResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<SongjiangheMahjongReplayResponse>
                PARSER = new com.google.protobuf.AbstractParser<SongjiangheMahjongReplayResponse>() {
            public SongjiangheMahjongReplayResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new SongjiangheMahjongReplayResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<SongjiangheMahjongReplayResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<SongjiangheMahjongReplayResponse> getParserForType() {
            return PARSER;
        }

        public game.mode.Songjianghe.SongjiangheMahjongReplayResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SongjiangheMahjongIntoResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SongjiangheMahjongIntoResponse_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SongjiangheMahjongReplayResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SongjiangheMahjongReplayResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021songjianghe.proto\032\016gameBase.proto\032\rmah" +
                        "jong.proto\"\210\001\n\036SongjiangheMahjongIntoRes" +
                        "ponse\022\021\n\tbaseScore\030\001 \001(\r\022\021\n\tgameTimes\030\002 " +
                        "\001(\r\022\021\n\tgameRules\030\003 \001(\r\022\r\n\005ghost\030\004 \001(\r\022\017\n" +
                        "\007maCount\030\005 \001(\r\022\r\n\005count\030\006 \001(\r\"\224\001\n Songji" +
                        "angheMahjongReplayResponse\022$\n\005start\030\001 \001(" +
                        "\0132\025.MahjongStartResponse\022\"\n\007history\030\002 \003(" +
                        "\0132\021.OperationHistory\022&\n\006result\030\003 \001(\0132\026.M" +
                        "ahjongResultResponseB\013\n\tgame.modeb\006proto" +
                        "3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                                game.mode.GameBase.getDescriptor(),
                                game.mode.Mahjong.getDescriptor(),
                        }, assigner);
        internal_static_SongjiangheMahjongIntoResponse_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SongjiangheMahjongIntoResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SongjiangheMahjongIntoResponse_descriptor,
                new java.lang.String[]{"BaseScore", "GameTimes", "GameRules", "Ghost", "MaCount", "Count",});
        internal_static_SongjiangheMahjongReplayResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SongjiangheMahjongReplayResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SongjiangheMahjongReplayResponse_descriptor,
                new java.lang.String[]{"Start", "History", "Result",});
        game.mode.GameBase.getDescriptor();
        game.mode.Mahjong.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
